- RestSharp.IntegrationTests/AsyncTests.cs
- RestSharp.IntegrationTests/NonProtocolExceptionHandlingTests.cs
- RestSharp/Http.Async.cs
- RestSharp/RestClient.Async.cs
This issue seems to plague a lot of people.
Execute (sync) and ExecuteAsync handle exceptions by swallowing them and setting the Error properties on the response object. This change makes ExecuteTaskAsync also swallow its errors by NOT invoking  taskCompletionSource.TrySetException(response.ErrorException) in RestClient.Async.cs.
The change in Http.Async.cs was simply to populate the ErrorException with a ResponseStatus.ToWebException() if empty, making it even more consistent with Execute (sync).
Most of the code changes were changes to tests that expected ExecuteTaskAsync to throw exceptions.
> Fix to issue in #466 and others. ExecuteTaskAsync should not throw exceptions

- RestSharp/Http.Async.cs
- RestSharp/Http.Sync.cs
ServicePointManager.Expect100Continue = false;
with
webRequest.ServicePoint.Expect100Continue = false;
The original version sets the default for all *future* ServicePoints, but not the
current ServicePoint. I don't think setting the global default here is a
great idea, and it doesn't even affect the current ServicePoint which has
already been created.
Setting the application global default down inside a library is a bad behavior to me. This could lead to unintended results elsewhere in the application that incorporates RestSharp.
I posted in the Google Group if anyone wants to discuss or would like more explanation.
> ServicePointManager to ServicePoint Change

- RestSharp.IntegrationTests/MultipartFormDataTests.cs
- RestSharp.IntegrationTests/RestSharp.IntegrationTests.csproj
- RestSharp.IntegrationTests/packages.config
- RestSharp.Net4/RestSharp.Net4.csproj
- RestSharp.Net4/packages.config
Using `Environment.NewLine` instead of hardcoding `\r\n`.  Hoping this fixes any previous issues with AppVeyor.  Only way to test for me is to push the PR.
Also removed all references to NUnit.
> Attempt to fix AppVeyor integration test issues with XUnit.

- RestSharp.Build/RestSharp.Build.csproj
`RestSharp.Build` project post-build event fails with `Copy` command unless this fix is put in.
> Add double quotes in post build event to prevent errors in paths with spaces.

- package.cmd
- packageSigned.cmd
Since RestSharp.WindowsPhone is now a wp8 library we should stop creating the nuget package with it as a wp7.1 library.
> Replace `sl4-wp71` in nuget packages with `windowsphone8`

- RestSharp.Tests/JsonTests.cs
- RestSharp.Tests/SampleClasses/misc.cs
- RestSharp.Tests/SampleData/timespans.txt
- RestSharp/Deserializers/JsonDeserializer.cs
It appears that ServiceStack's default serialization for TimeSpan is ISO 8601, which causes an exception during deserialization in RestSharp. XmlConvert handles this format, so we'll attempt normal TimeSpan.Parse and failing that, attempt XmlConvert.
> Adding support for deserializing ISO 8601 durations as TimeSpan in JSON

- RestSharp.Tests/RestSharp.Tests.csproj
- RestSharp.Tests/SampleClasses/Goodreads.cs
- RestSharp.Tests/SampleData/Goodreads.xml
- RestSharp.Tests/XmlDeserializerTests.cs
- RestSharp/Deserializers/XmlDeserializer.cs
I closed the previous request and i am adding a new one with unit test, that show the issue
> Make the attributes search work the same as for elements

- RestSharp/IRestRequest.cs
- RestSharp/RestRequest.cs
now it's possible to upload a file with a correct content-type
> added IRestRequest AddFile(string name, string path, string contentType)

- RestSharp.Tests/AddRangeTests.cs
- RestSharp.Tests/RestSharp.Tests.csproj
- RestSharp/Http.cs
Here's a quick attempt to fix the #636 AddHeader
> Fixes #636 - Header of 'Range' now supports a rangeSpecifier

- RestSharp/SimpleJson.cs
Now you can use json.name instead of json["name"]
> DynamicObject Support for .Net4+

- RestSharp.IntegrationTests/MultipartFormDataTests.cs
- RestSharp/Http.Sync.cs
Issue #672 
Changed `Http.Sync.cs` method `WriteRequestBody` internals for change.
Added unit tests.
> Issue 672 Fix

- RestSharp/Http.Async.cs
- RestSharp/Http.Sync.cs
- RestSharp/Http.cs
- RestSharp/IHttp.cs
- RestSharp/IRestClient.cs
- RestSharp/RestClient.cs
This is to address [issue #403](https://github.com/restsharp/RestSharp/pull/403) previously raised to allow access to the caching policy within the context of a specific RestClient. It is based on the code produced for [issue #401](https://github.com/restsharp/RestSharp/pull/401), which was potentially breaking. This change is more limited, as it does not change default behavior.  I have tried this locally, and the cache policy works when applied, and there is no change when the cache policy remains unset.
> Added cache policy property to client.

- RestSharp.Tests/JsonTests.cs
- RestSharp.Tests/RestSharp.Tests.Signed.csproj
- RestSharp.Tests/RestSharp.Tests.csproj
- RestSharp.Tests/SampleData/jsondictionary_KeysType.txt
- RestSharp/Deserializers/JsonDeserializer.cs
I use a json data what use integer keys. And currently change my dictionary type as <string, string> for use restsharp deserializer. I think its fix dictionary key type for what dictionary contains.
> JsonDeserializer Dictionary Key Type

- RestSharp.IntegrationTests/RestSharp.IntegrationTests.csproj
- RestSharp.IntegrationTests/StructuredSyntaxSuffixTests.cs
- RestSharp/RestClient.cs
As per https://tools.ietf.org/html/rfc6839#section-3,
> `3.  Initial Structured Syntax Suffix Definitions
>
> 3.1.  The +json Structured Syntax Suffix
>
>   [RFC4627] defines the "application/json" media type.  The suffix
"+json" MAY be used with any media type whose representation follows
that established for "application/json".
A similar approach is used for XML (``+xml``).
Essentially, what this means is that a JSON request body could be presented with a content type of ``application/json`` or it could use a content type with a structured syntax suffix of ``+json``.  For example, ``application/vnd.somebody.something+json`` should be treated the same way as ``application/json`` by the ``RestClient``.
This commit adds support for handling content types with structured syntax suffixes on …
> Add support for deserializing content types using "Structured Syntax Suffixes"

- RestSharp/RestResponse.cs
One of the biggest pet peeves of RestSharp is the lack of Debugger Visualizations. This pull request is an attempt to show that a simple change can make a huge difference in the debug experience.
##Current
##With PR
The big change that I want is to easily see the HTTP Status Code, beyond that I'm open to any and all suggestions and feedback.
Thank you.
> Enhance Debug experience w/ RestResponse

- RestSharp.Tests/JsonTests.cs
- RestSharp/Deserializers/JsonDeserializer.cs
It should fix #635 . I added a unit test for it as well. Now `JsonTests.Can_Deserialize_To_Dictionary_Int_Object` is not passing, but I'm not sure if it a correct test actually, since deserialization of `Dictionary<TKey, TValue>` where `TKey` is not `string` doesn't seem to be supported.
> Allow deserialization of base types from JSON 

- RestSharp.Tests/JsonTests.cs
- RestSharp.Tests/RestSharp.Tests.Signed.csproj
- RestSharp.Tests/RestSharp.Tests.csproj
- RestSharp.Tests/SampleData/jsondictionary_null.txt
- RestSharp/Deserializers/JsonDeserializer.cs
> Do not create empty objects in case of null

- RestSharp/IRestRequest.cs
- RestSharp/RestRequest.cs
Adding required input of content length when adding a file using a writer action.
> Fix content length of file parameter

- RestSharp.Tests/JsonTests.cs
- RestSharp/Extensions/StringExtensions.cs
ParseJsonDate detects if the given long is outside the allowed range and tries to add it as milliseconds instead of seconds.
This was a problem for me when using Dates generated with Java (Date.getTime()).
> Detection of millisecond-timestamps

- index.html
Running the example as-is throws `DNX,Version=v4.5.1 error CS0266: Cannot implicitly convert type 'RestSharp.IRestResponse' to 'RestSharp.RestResponse'. An explicit conversion exists (are you missing a cast?)` under .NET Core.
Happy to be told I'm wrong :)
> Change RestResponse to IRestResponse in sample code

- RestSharp.Tests/JsonTests.cs
- RestSharp/Deserializers/JsonDeserializer.cs
Bug fix for JsonDeserialize to support type of IEnumerable. If the given
property is IEnumerable, create a new list using the same generic
argument.
> JsonDeserializer support for IEnumerable

- RestSharp/Http.cs
- RestSharp/HttpResponse.cs
- RestSharp/IHttpResponse.cs
- RestSharp/IRestResponse.cs
- RestSharp/RestClient.cs
- RestSharp/RestResponse.cs
It is only set in FRAMEWORK builds, but is available as the default on any platform.
Fixes #790
> Added ProtocolVersion to RestResponse.

- RestSharp.Tests/OAuthTests.cs
- RestSharp/Authenticators/OAuth/Extensions/OAuthExtensions.cs
- RestSharp/Authenticators/OAuth/OAuthSignatureMethod.cs
- RestSharp/Authenticators/OAuth/OAuthTools.cs
- RestSharp/Authenticators/OAuth1Authenticator.cs
I needed support for HMAC-SHA256 for a project
> Added HMAC-SHA256 as a signature method to OAUTH1

- RestSharp.Tests/RestRequestTests.cs
- RestSharp/RestRequest.cs
AddUrlSegment overload method to allow pass object as value so that
calling ToString() on value is not needed.
Let say one would like to send request to API endpoint `api/document/{documentId}/details` and there is method:
```c#
public IList<DocumentDetails> GetDetails(int documentId)
{
var request = new RestRequest("api/document/{documentId}/details");
request.AddUrlSegment("documentId", documentId.ToString());
...
}
```
It would be nice not to have to call ToString() method on documentId. Just like this:
```c#
public IList<DocumentDetails> GetDetails(int documentId)
{
var request = new RestRequest("api/document/{documentId}/details");
request.AddUrlSegment("documentId", documentId);
...
}
```
In my opinion this is more convenient and also thanks to it code is a little bit more cleaner.
> AddUrlSegment overload

- RestSharp/Http.Sync.cs
ability to set HttpHeader 'Connection' to 'keep-alive' or 'close' using the existing header dictionary
> support added for #781: Keep-Alive Functions

- RestSharp.Net45/RestSharp.Net45.Signed.csproj
- RestSharp.Net45/RestSharp.Net45.csproj
- RestSharp.Net451/RestSharp.Net451.Signed.csproj
- RestSharp.Net451/RestSharp.Net451.csproj
- RestSharp.Net452/RestSharp.Net452.Signed.csproj
- RestSharp.Net452/RestSharp.Net452.csproj
- RestSharp.Net46/RestSharp.Net46.Signed.csproj
- RestSharp.Net46/RestSharp.Net46.csproj
- RestSharp/Http.Async.cs
- RestSharp/Http.Sync.cs
- RestSharp/Http.cs
- RestSharp/IHttp.cs
- RestSharp/IRestClient.cs
- RestSharp/RestClient.cs
Fixes #620 by adding a ```RemoteCertificateValidationCallback``` on ``IRestClient`` and passing it all the way to the creation of the ```HttpWebRequest``` for custom per-request certificate validation.
> Add RemoteCertificateValidationCallback for .NET 4.5 and Above via RestClient

- RestSharp/Http.Async.cs
- RestSharp/Http.cs
- RestSharp/IHttp.cs
- RestSharp/IRestClient.cs
- RestSharp/RestClient.cs
I came across to a similar problem as in #770. When having multiple requests at the same sometimes responses got mixed up or some responses got lost. Having Pipelined set as false fixed the problem.
> Possibility to change Pipelined property of WebRequest

- RestSharp/RestRequest.cs
Original documentation appeared to be a copy/paste of RestRequest.XmlSerializer's documentation.
> Fix RestRequest.RequestFormat documentation.

- RestSharp/IRestClient.cs
- RestSharp/RestClient.cs
I created this public method so that callers could choose to deserialize a response into a particular type based on the status code provided in the response.
This should resolve #774
> Implemented public Deserialize<T> method on RestClient

- RestSharp/Extensions/MonoHttp/HtmlEncoder.cs
Wrapped memory stream in HtmlEncode.cs into a using for fixing improper resource shutdown or release (found by Veracode static scan).
> Wrapped memory stream into a using in HtmlEncode.cs

- RestSharp.Tests/JsonTests.cs
On some system cultures (for example ru-RU), "Can_Deserialize_DateTime_With_DateTimeStyles" test is failing, because of implicit Date.ToString() call.
Now leave conversion of dates to JsonDeserializer.
> fixed failing Can_Deserialize_DateTime_With_DateTimeStyles test

- RestSharp/RestClient.cs
This is perfomance problem. When we created class RestClient, it is checked AddHandler, but we create new regexp every time. And this is very long operation. If use static, this operation very fast.
Example:
for (var i = 0; i < 1000; i++)
{
var client = new RestSharp.RestClient( new Uri("https://api-maps.yandex.ru/2.1/"));
}
with static - 0.07s
without static - 5s
msdn is written regex is Thread Safety - https://msdn.microsoft.com/en-us/library/6h453d2h(v=vs.110).aspx
> changed Regex suffix to static

- RestSharp.Tests/SampleClasses/misc.cs
- RestSharp.Tests/XmlDeserializerTests.cs
- RestSharp/Deserializers/XmlDeserializer.cs
When a class has a property named Value corresponding to an XML attribute inside an element, which is not the root element, then deserialization is failing only for that property.
> Fix attribute being deserialized as parent element when named Value

- RestSharp/RestSharp.Net35.Signed.csproj
Existing build errors as:
Error CS1577: Referenced assembly `RestSharp.Build, Version=1.0.0.0,
Culture=neutral, PublicKeyToken=null' does not have a strong name
(CS1577) (RestSharp.Net35.Signed)
IDE: Xamarin Studio
OS: OS X El Capitan
> Fixed reference to RestSharp.Build.Signed

- RestSharp.Tests/UrlBuilderTests.cs
- RestSharp/RestClient.cs
- RestSharp/RestSharp.csproj
Details in the test case and this issue: https://github.com/restsharp/RestSharp/issues/1035
```
RestRequest request = new RestRequest("https://www.example1.com/connect/authorize");
RestClient client = new RestClient("https://www.example1.com/");
Uri expected = new Uri("https://www.example1.com/connect/authorize");
```
> Fixed Uri builder when the Resource is an absolute Uri (with protocol, etc...).

- RestSharp.Tests/OAuthTests.cs
- RestSharp/Authenticators/OAuth/OAuthTools.cs
Supports OAuthSignatureMethod.RsaSha1, useful for integrations with RSA SHA1-based OAuth integrations such as Atlassian JIRA's REST API. I've tested this against my company's JIRA Server 7.2.2 instance, as well as with the unit tests included in the PR.
> Add RSA-SHA1 signing capability

- RestSharp.Tests/StringExtensionsTests.cs
- RestSharp.Tests/UrlBuilderTests.cs
- RestSharp/Extensions/StringExtensions.cs
- RestSharp/RestClient.cs
No matter what encoding I selected, the Url query string parameters were
always encoded using the default UTFencoding.
Reason: i needed to call a GET method that required me to send my query
string encoded in ISO-8859-1 encoding. I tried many options but 'ø'
would always become '%C3%B8' even though I had set the encoding property
to ISO-8859-1 which should get me '%F8'
This change uses the currently selected encoding in the RestClient.cs
and uses it to encode parameters and names instead of using UrlEncode
which (although works for most cases) might not work for everybody.
> query string parameters are encoded correctly using the selected encoding instead of default encoding

- RestSharp.IntegrationTests/StatusCodeTests.cs
- RestSharp/Http.cs
Fixes #784 where users were unable to set a custom content type because it was being overwritten by the content type of the body.
> User set Content-Type was being by the content type of the body

- RestSharp/Http.Async.cs
- RestSharp/Http.Sync.cs
- RestSharp/Http.cs
- RestSharp/IHttp.cs
- RestSharp/IRestClient.cs
- RestSharp/RestClient.cs
Add UnsafeAuthenticatedConnectionSharing flag to RestClient so that we
can set it to the underlying webrequest.
> Add UnsafeAuthenticatedConnectionSharing flag to RestClient

- RestSharp.Tests/Extensions/RSACryptoServiceProviderExtensionsTests.cs
- RestSharp/Authenticators/OAuth/OAuthTools.cs
- RestSharp/Extensions/RSACryptoServiceProviderExtensions.cs
There are some issues on .NET's side about the
missing functionality of RSACryptoServiceProvider
ToXmlString/FromXmlString:
* https://github.com/dotnet/corefx/issues/23686
* https://github.com/dotnet/core/issues/874
So, let's do it ourselves, and if in the future we'll
get it in the .NET itself, we can remove this code
@alexeyzimarev Would be awesome if we could get a release with this fix, right now we can't use the library in a .NET Core 2.0 & OAuth 1 app .
> Handle RsaSha1 properly in .NET Core 2.0

- RestSharp/Extensions/StringExtensions.cs
- RestSharp/Http.cs
- RestSharp/RestClient.cs
- RestSharp/RestRequest.cs
https://github.com/restsharp/RestSharp/issues/899
- [X ] Performance improvement
> Don't use compiled Regexes and make sure they are all static

- RestSharp.IntegrationTests/RequestBodyTests.cs
- RestSharp/RestClient.cs
Fixes the descripte issue in #1134 
> Option AlwaysMultipartFormData with AddParamter(name, value contentType, ParameterType.RequestBody) without file breaks the request

- RestSharp/RestClientExtensions.cs
Method parameter to client.Execute should be Method.POST, not Method.PUT.
- [ X] Bugfix (non-breaking change which fixes an issue)
> Mistake in Post extension method

- RestSharp.Tests/SimpleJson.cs
- RestSharp.Tests/SimpleJsonTests.cs
- RestSharp/SimpleJson.cs
If a valid json-formatted string is passed into AddJsonBody or AddBody it will be added with double escape characters for every escape-required character. The issue is in how SimpleJson implements serialization. This fix detects valid json and avoids modifying it.
> Fixed double escape bug in SimpleJson

- RestSharp.Tests/JsonTests.cs
- RestSharp.Tests/SimpleJsonTests.cs
- RestSharp/Serializers/JsonSerializer.cs
Fixing the double escape issue highlighted here https://github.com/restsharp/RestSharp/issues/1199 and https://github.com/restsharp/RestSharp/pull/1185.
While also still handling the scenario where the object may contain strings that appear to be json https://github.com/restsharp/RestSharp/issues/1189.
> JsonSerializer to skip serialization of json strings

- RestSharp/Authenticators/HttpBasicAuthenticator.cs
Fixed NullReferenceException from HttpBasicAuthenticator when a parameter name is null
> Fixed #881

- RestSharp.IntegrationTests/FileTests.cs
- RestSharp/Http.cs
1. Moved ProcessResponseStream() call to the bottom of ExtractResponseData() to make HttpResponse members available to AdvancedResponseWriter.
2. Check for AdvancedResponseWriter first and call only that or fallback to ResponseWriter.
> Better use of AdvancedResponseWriter

- RestSharp/RestRequest.cs
Fix typo "_alloweDecompressionMethods" to "_allowedDecompressionMethods".
I've added description of the typo fix in the commit description.
> Fix typo in RestRequest.cs

- RestSharp.Tests/JsonTests.cs
- RestSharp/Serialization/Json/JsonSerializer.cs
I was encountering issues deserializing json with objects that defined IList<> types.  This is very similar to how IEnumerable is handled in existing code.
> Add ability to deserialize an IList<> object, by creating a List<>

- RestSharp.IntegrationTests/ProxyTests.cs
One integration proxy test is failing on non-EN environments due to checking localized ErrorMessage. This is resolved by checking Status (exception type) instead.
> Fixed proxy tests for localized environments

- RestSharp.Tests/JsonTests.cs
- RestSharp/Serialization/Json/JsonSerializer.cs
This is an expansion on #1201 which allowed JsonSerializer to handle already serialized strings.
[ { "key", "value"} ] Is also valid json and could be sent as a string. The Serialize method should handle all valid json formats.
I chose to move IsSerializedString to its own method because it was beginning to create readability issues in the Serialize method.
Please let me know if anything needs to be cleaned up in my changes!
> An array of objects is also valid Json and should be handled by JsonSerializer.

- RestSharp.Tests/RestRequestTests.cs
- RestSharp.Tests/TestData/JsonData.cs
- RestSharp/RestRequest.cs
Do not encode querystring parameters that are sent to the RestRequest constructor. Also fix unit tests that were failing from range change.
Issue 1273
I don't know how to check one box. It is fixing an existing issue that was a breaking change. This reverts it back to the behavoir in 106.6.4
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] I have added tests that prove my fix is effective or that my feature works
> Issue 1273

- RestSharp/RestSharp.csproj
106.6.8 exposes a unnecessary dependency on `Microsoft.SourceLink.GitHub`.
From https://github.com/dotnet/sourcelink#githubcom-and-github-enterprise
> Source Link package is a development dependency, which means it is only used during build. It is therefore recommended to set PrivateAssets to all on the package reference. This prevents consuming projects of your nuget package from attempting to install Source Link.
> Make SourceLink a development dependency only

- RestSharp.IntegrationTests/RestSharp.IntegrationTests.csproj
- build.bat
Using `/p:DefineConstants` doesn't add `APPVEYOR` as a constant, but sets it as the *only* defined constant. 
This fixes #1294 
I'm not entirely sure how to add a test to ensure this, but I inspected the compiled dlls using `ILSpy` after running `build.bat`
`net452`
```c#
webRequest.UnsafeAuthenticatedConnectionSharing = UnsafeAuthenticatedConnectionSharing;
try
```
`netstandard2.0`
```c#
webRequest.UnsafeAuthenticatedConnectionSharing = UnsafeAuthenticatedConnectionSharing;
webRequest.Proxy = null; // <--- this is what we want
try
```
Inspecting `RestSharp.IntegrationTests.dll` also showed, that `Can_Cancel_GET_TaskAsync()` was correctly excluded as expected when running `build.bat` and included when building otherwise.
> Add APPVEYOR constant instead of replacing existing constants

- RestSharp.IntegrationTests/RootElementTests.cs
- RestSharp.IntegrationTests/SampleDeserializers/CustomDeserializer.cs
- RestSharp/RestClient.cs
- RestSharp/Serialization/Xml/IXmlDeserializer.cs
When you set request's RootElement property, that's not setting back in deserializer's RootElement.
> Fix setting deserializer's RootElement from request's RootElement

- RestSharp/IRestRequest.cs
Add IRestRequest AddUrlSegment(string name, object value) to maintain consistency with implementation class RestRequest
The implementation class RestRequest have two methods: 
`public IRestRequest AddUrlSegment(string name, object value)`
`public IRestRequest AddUrlSegment(string name, string value)`
But in `IRestRequest` don't have this method:
`public IRestRequest AddUrlSegment(string name, object value)`
It's cause a problem that the user call `AddUrlSegment(string name, object value)` twice, in second call, the return of `IRestRequest` force the user a send two `strings` instead `<string, object>`
- [X ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> Add method in Interface

- RestSharp/IRestRequest.cs
- RestSharp/RestClient.Async.cs
- RestSharp/RestClient.Sync.cs
- RestSharp/RestRequest.cs
The callback/event `OnAfterConfiguration` is executed after the HTTP object is configured, but before the HTTP request is made. This allows for some last minute header modifications, which in my case is necessary due to the delayed serialization in 106.6 and later.
I've tested using `OnAfterConfiguration` instead of setting `RestClient.Authenticator`, and it seems to do the trick.
Solves issue #1305 
> Add callback/event RestRequest.OnBeforeRequest

- RestSharp.Tests/XmlSerializerTests.cs
- RestSharp/Serialization/Xml/XmlSerializer.cs
IList properties marked with [SerializeAs(Content = true)] attribute can be serialized as parent's XML tag content.
In this thread you'll find more info: https://stackoverflow.com/questions/56849421/serialize-list-property-as-parents-content-with-restsharp-xmlserializer
> Make use SerializeAs(Content = true) attribute for IList properties.

- RestSharp.Tests/RequestHeaderTests.cs
- RestSharp/IRestRequest.cs
- RestSharp/RestRequest.cs
I've implemented a simple utility feature to take a KeyValuePair collection (Dictionary, etc.) and add headers to the RestRequest from the given collection.
> AddHeaders Implementation for RestRequest

- RestSharp.IntegrationTests/DefaultParameterTests.cs
- RestSharp/RestClient.cs
Solves issue #1378 , only the bugfix part, the part that requested to unable creating null default parameter is a breaking change so I didnt change it.
- [ x] Bugfix (non-breaking change which fixes an issue)
- [x ] I have added tests that prove my fix is effective or that my feature works
> Fix issue #1378

- RestSharp.Tests/RestClientTests.cs
- RestSharp/RestRequest.cs
Got an error when i am trying to do a request with passing url as Uri
"Request resource doesn't contain a valid scheme for an empty client base URL".
if i pass url as a string it works well.
i created some tests to show the problem
> throws an exception if pass an url as Uri class in RestRequest and do a request

- RestSharp/Authenticators/HttpBasicAuthenticator.cs
*I've been experimenting [authentication issues ](https://bitbucket.org/farmas/atlassian.net-sdk/wiki/Home) with Jira .NET Api (which uses RestSharp under the hood).  When using french character 'é' I couldn't authenticate. It turns out that the Jira server expects ISO-8859-1 encoding.*
This pull request allows to use ISO-8859-1 encoding for the BASIC header.  Default encoding remains UTF-8.
In this thread you'll find some more info: https://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication  
> Allows ISO-8859-1 encoding for basic authentication

- docs/get-help/faq.md
- docs/usage/exceptions.md
Modify to the correct property name
> Modify docs

- src/RestSharp/RestRequest.cs
A different attempt at fixing #1404 then what was proposed in #1408.
But even this is not a perfect solution, as explained in https://github.com/restsharp/RestSharp/pull/1408#issuecomment-575213217 and https://github.com/restsharp/RestSharp/pull/1408#issuecomment-575596890.
Someone with more knowhow should probably rewrite the entire [`ParseQuery(string)`](https://github.com/restsharp/RestSharp/blob/master/src/RestSharp/RestRequest.cs#L83) method. Or even better find a more standard way of doing it that doesn't require us to maintain the function ourselves.
For a good idea about how the query parsing should handle can be seen in this little article: https://zzzzbov.com/blag/query-string-hell
This pull request is a: Bugfix (non-breaking change which fixes an issue)
> Ignore Empty Uri Query Parameters

- src/RestSharp/RestClient.cs
https://github.com/restsharp/RestSharp/issues/1280#issuecomment-580308487
- Bugfix
> Fixing comment in #1280

- src/RestSharp/Serializers/Xml/XmlDeserializer.cs
- test/RestSharp.Tests/RestSharp.Tests.csproj
- test/RestSharp.Tests/SampleData/GoodreadsFormatError.xml
- test/RestSharp.Tests/XmlDeserializerTests.cs
Fixed format exception error
Add property name to the FormatException
> Add property name to the FormatException #1452

- src/RestSharp/Http.cs
- src/RestSharp/IHttp.cs
- test/RestSharp.IntegrationTests/MultipartFormDataTests.cs
- test/RestSharp.IntegrationTests/RequestBodyTests.cs
The request body might contain the previous, fixed value for FormBoundary.
This will cause a server to split the body on the wrong boundaries.
For example trying to post this file which already contains a boundary will generate an invalid request.
`-------------------------------28947758029299
Content-Disposition: form-data; name="somefile_REC.pdf"; filename="somefile_REC.pdf"
Content-Type: application/x-gzip
%PDF-1.4
[...] truncated
%%EOF
-------------------------------28947758029299--
`
By using a random value for the boundary collisions like this will be avoided.
> Use random value for multipart/form-data boundary.

- src/RestSharp/Extensions/StringExtensions.cs
Use given culture when call `.ToLower`
The function `MakeInitialLowerCase` have breaking change. We can decide to use `CultureInfo.InvariantCulture` as default fallback.
Fix for Issue: https://github.com/restsharp/RestSharp/issues/1491
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x ] I have added tests that prove my fix is effective or that my feature works
> Fix culture

- src/RestSharp/Authenticators/OAuth/Extensions/OAuthExtensions.cs
- src/RestSharp/Authenticators/OAuth/OAuthTools.cs
- src/RestSharp/Http.cs
- src/RestSharp/RestClient.cs
- src/RestSharp/Serializers/SerializeAsAttribute.cs
- src/RestSharp/Serializers/Xml/XmlDeserializer.cs
In reference to #1472 and #1492 I found some more code places where no culture is used.
e.g. `XMLSerializer` contains a `CultureInfo`. This will should be used for all `.ToLower()` calls.
e.g. `Http` contains no `CultureInfo`. I have changed `.ToLower()` to `.ToLowerInvariant()`.
- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ x ] I have added tests that prove my fix is effective or that my feature works
> Ensure the correct culture is used

- src/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs
- test/RestSharp.Tests/OAuth1AuthenticatorTests.cs
In reference to #1495 
According to RFC, the `oauth_token` must be encoded.  Some OAuth providers return token that contains `=` symbol, the current implementation doesn't encode it to %3D.  This PR adding encoding for `oauth_token`.
> Encode oauth_token. Fixes #1495

- src/RestSharp/Http.Sync.cs
- src/RestSharp/Http.cs
- src/RestSharp/RestClient.cs
- test/RestSharp.Tests/RestRequestTests.cs
fix #1511 
RestClient property ThrowOnAnyError is not work correct becouse all exceptions are handled before this check:
```C#
try
{
var http = ConfigureHttp(request);
request.OnBeforeRequest?.Invoke(http);
response = RestResponse.FromHttpResponse(getResponse(http, httpMethod), request);
}
catch (Exception ex)
{
if (ThrowOnAnyError) throw;
response.ResponseStatus = ResponseStatus.Error;
response.ErrorMessage   = ex.Message;
response.ErrorException = ex;
}
```
In getResponse we have:
```C#
catch (Exception ex)
{
return ExtractErrorResponse(ex);
}
```
> fix: throw error if ThrowOnAnyError flag is true

- docs/getting-started/README.md
changed tha to who which I feel is more appropriate.
> Changed tha to who

- src/RestSharp/Http.Async.cs
This bugfix is a PR for @WayneHiller's find of a memory leak in async calls. Verified independently on .NET Core 3.1
I am making the PR to be the one available to handle issues related to getting this bugfix into an upcoming release (it seems there has been some issue with the versioning)
> fix memory leak #1506

- src/RestSharp/RestResponse.cs
This resolves issue #1547 and related issues
> mark ErrorException as nullable to match interface

- src/RestSharp/Extensions/StringExtensions.cs
- test/RestSharp.Tests/JsonTests.cs
- test/RestSharp.Tests/RestSharp.Tests.csproj
- test/RestSharp.Tests/SampleClasses/misc.cs
- test/RestSharp.Tests/SampleData/newdatetimes.json
Fixes #1556.
I think it should be a non-breaking change. Feel free to edit this PR as I don't usually do .NET development.
> Fix NewDateRegex in StringExtensions #1556

- docs/usage/serialization.md
All other includes of properties or other imp things are with grey background but here in this case Utf8Json wasn't there with grey background. It's a minor change but as a reader anyone can figure it out the difference. I hope you will consider this change as it is small but an important Visual change.
This pull request does not any code related issue but particularly a display related important issue from Docs. All important words like properties are in grey color but Utf8Json does not have any grey background color and this difference can be spotted while reading the docs.
This pull request is a:  Bugfix (non-breaking change which fixes an issue)
- [x ] Bugfix (non-breaking change which fixes an issue)
> Important change in Docs in Utf8Json

- src/RestSharp/Serializers/Json/JsonSerializer.cs
- test/RestSharp.Tests/JsonTests.cs
- test/RestSharp.Tests/SampleClasses/misc.cs
- test/RestSharp.Tests/TestData/JsonData.cs
This addresses an issue brought up in #1471 where attributes that ended in "ID" (or any sequence of upper-case letters) was not able to match with properties where those two letters were also both capitalized (i.e. "id", "Id").  I didn't see in the docs that case-insensitive matching was a requirement, but for many people it seems that it is implied.
Addressing this issue in the GetNameVariants method in StringExtensions.cs would seem to involve a lot of extra methods just to achieve a case-insensitive comparison, so I updated the Map method to create a new case-insensitive dictionary rather than simply referencing the previous one.
- [x ] Bugfix (non-breaking change which fixes an issue)
- [ x] I have added tests that prove my fix is effective or that my feature …
> Double uppercase issue

- src/RestSharp/Extensions/ReflectionExtensions.cs
- src/RestSharp/Serializers/Json/JsonSerializer.cs
When deserializing any primitive type (floating point types especially), the JsonSerializer uses Convert.ChangeValue without passing Culture property, which results in using CurrentCulture as default.
I don't seem to find any other effective way how to enforce the RestSharp to deserialize primitive value using using custom Culture.
> JsonSerializer does not respect Culture when deserializing primitive types

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
- ready-to-start GitHub Codespaces configuration
- it provides basic tools for:
- .NET development
- GitHub support
- overall more pleasant VS Code experience
The configuration consists of:
- `"settings":` - a list of VS Code settings to be applied automatically after the Codespace container is created (.editorconfig overrides these)
- `"workbench.colorTheme": "Default Dark+"` - sets the theme of the VS Code workbench to the `Default Dark+` theme
- `"terminal.integrated.defaultProfile.linux": "pwsh"` - sets the default VS Code terminal to PowerShell Core
- `extensions:` - a list of VS Code extensions that are automatically installed after the Codespace container is created
- `"eamodio.gitlens"` - provides git information directly inside the code
- `"ms-dotnettools.csharp"` and …
> Resolves: Add GitHub Codespaces configuration

- src/RestSharp/IRestRequest.cs
- src/RestSharp/RestRequest.cs
- test/RestSharp.Tests/RequestHeaderTests.cs
Implement the AddOrUpdateHeader and AddOrUpdateHeaders methods as discussed in #1569 
> Implement "AddOrUpdateHeader(s)" methods

- src/RestSharp/Authenticators/OAuth/OAuth1Authenticator.cs
- src/RestSharp/Authenticators/OAuth/OAuthTools.cs
- src/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs
- test/RestSharp.Tests/OAuth1AuthenticatorTests.cs
OAuth 1.0a specifications allow to use of an empty custom secret (see [here](https://oauth.net/core/1.0a/, section 4: _The Consumer Secret MAY be an empty string [..]_). Similarly to #776, I needed to call MAAS API, where the customer secret must not be provided (0-legged OAuth). This pull request removes the constraint of providing customer secrets for OAuth1.
This has been tested over the API of MAAS, which does not require any customer secret.
Don't hesitate to ask for changes in that pull request if needed.
Cheers
> OAuth1: Allow empty customer secrets, according to the specifications.

- src/RestSharp/Extensions/ReflectionExtensions.cs
Avoid null exception, and return better error info for client/server enum mismatch.
This simple suggestion fixes #1614.
(I had a quick look, but didn't see a similar test that I could re-use for this case.)
> Better enum deserialization exception fixes #1614

- docs/usage/authenticators.md
Authenticator documentation updates.
- [ x] New feature (non-breaking change which adds functionality)
- [x ] I have added necessary documentation (if appropriate)
> Authenticator documentation updates

- src/RestSharp/Extensions/MiscExtensions.cs
- src/RestSharp/Parameters/BodyParameter.cs
- src/RestSharp/Parameters/FileParameter.cs
- src/RestSharp/Parameters/HeaderParameter.cs
- src/RestSharp/Parameters/Parameter.cs
- src/RestSharp/Parameters/ParametersCollection.cs
- src/RestSharp/Parameters/UrlSegmentParameter.cs
- src/RestSharp/Request/BodyExtensions.cs
- src/RestSharp/Request/HttpRequestMessageExtensions.cs
- src/RestSharp/Request/RequestContent.cs
- src/RestSharp/Request/RequestHeaders.cs
- src/RestSharp/Request/RestRequest.cs
- src/RestSharp/Request/RestRequestExtensions.cs
- src/RestSharp/RestClient.Async.cs
- src/RestSharp/RestClient.Serialization.cs
- src/RestSharp/RestClient.cs
- src/RestSharp/RestClientExtensions.Json.cs
- src/RestSharp/Serializers/ContentType.cs
- test/RestSharp.Tests/ObjectParameterTests.cs
- test/RestSharp.Tests/ParametersTests.cs
- test/RestSharp.Tests/UrlBuilderTests.cs
- Add model binding extension
- Fix wrong content parameters for GET-style requests
> Model binding

- src/RestSharp/Extensions/MiscExtensions.cs
- src/RestSharp/KnownHeaders.cs
- src/RestSharp/Parameters/FileParameter.cs
- src/RestSharp/Parameters/GetOrPostParameter.cs
- src/RestSharp/Parameters/HeaderParameter.cs
- src/RestSharp/Parameters/QueryParameter.cs
- src/RestSharp/Parameters/UrlSegmentParameter.cs
- src/RestSharp/Request/RestRequest.cs
- src/RestSharp/Request/RestRequestExtensions.cs
- src/RestSharp/RestClientExtensions.Json.cs
- test/RestSharp.Tests/ParametersTests.cs
- Added generic overloads for request extensions that add parameters. It will be possible to use `string` or a struct (like `int`, `long`, etc), but not classes.
- Add missing optional `encode` argument to some extensions
- Removed the `ContentLength` requirement for file parameters as it's not used
> Cleaning up parameters

- src/RestSharp/Authenticators/AuthenticatorBase.cs
- src/RestSharp/Extensions/MiscExtensions.cs
- src/RestSharp/Response/ResponseHandling.cs
- src/RestSharp/Response/RestResponse.cs
- src/RestSharp/Response/RestResponseBase.cs
- src/RestSharp/RestClient.Async.cs
- src/RestSharp/RestClientExtensions.Json.cs
- src/RestSharp/RestClientExtensions.cs
- test/RestSharp.Tests.Shared/Extensions/StreamExtensions.cs
* Handle response content with custom encoding detection
* Add ConfigureAwait(false) to async calls
> Response handling improvements

- docs/v107/README.md
> doc: fixed return value of RestClient.PostAsync()

- docs/v107/README.md
I believe the *Ntlm*Authenticator was deprecated.
https://github.com/restsharp/RestSharp/blob/ca15b2599d9e85efd9ac43c7112188b9b0cc67a0/src/RestSharp/Authenticators/NtlmAuthenticator.cs#L23
> Fix typo in v107 documentation

- docs/v107/README.md
DownloadFileStreanAsync -> DownloadFileStreamAsync
Just fixes a tiny typo in the 107 migration docs
> fix: tiny typo

- src/RestSharp/RestClient.cs
* Add the possibility to configure default headers of HttpClient
> Add the possibility to configure default headers of HttpClient

- src/RestSharp/Request/RequestContent.cs
- test/RestSharp.Tests/RestContentTests.cs
If we add a content header to a request, but use non-standard casing (e.g., adding the header `content-type`), currently RestSharp doesn't correctly add this header to `HttpContent`, and then later it attempts to add it to `HttpRequest` and fails:
```
System.InvalidOperationException: Misused header name, 'content-type'. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.
at System.Net.Http.Headers.HttpHeaders.GetHeaderDescriptor(String name)
at System.Net.Http.Headers.HttpHeaders.Remove(String name)
at RestSharp.HttpRequestMessageExtensions.<AddHeaders>g__AddHeader|0_2(Parameter parameter, HttpHeaders httpHeaders)
at RestSharp.HttpRequestMessageExtensions.<>c__DisplayClass0_0.<AddHeaders>b__1( …
```
> Case insensitive header names

- docs/README.md
> Updated copyright

- src/Directory.Build.props
- src/RestSharp/Request/RequestContent.cs
- src/RestSharp/RestClient.cs
* Make `RestClient.Options` public, read-only
* Add a `RestClient` constructor with `HttpClient` only, which won't be changed in any way by RestSharp
> Proposed fix for #1765

- src/RestSharp/RestClient.cs
- src/RestSharp/RestClientOptions.cs
If you have a timeout on the client AND a timeout on the request, the resulting actual timeout is going to be the shorter of the two. By default HttpClient has a timeout of 100 seconds built in, so that means if someone is expecting to be able to send a request and have it wait longer than 100 seconds, it won't work unless the client is also changed.
So I propose we change the property in RestClientOptions which is then applied to HttpClient to be called MaxTimeout so it is a lot more clear what the connection is? You cannot have a longer timeout for any request unless you change this value.
It might also make sense to set this to a default value of something (maybe 100 seconds to make it clear) rather than leaving it null, so the user of the library will be more aware of how the client …
> Change RestClientOptions to MaxTimeout which is what it really is

- src/RestSharp/Response/RestResponse.cs
- src/RestSharp/Response/RestResponseBase.cs
These need to not be init only, because it can be quite useful to return mocked responses and it these are all init only, we cannot adjust them after creating a new instance.
I guess you could argue we should mock the class instead, so I could try that also, but is there any reason not to allow these properties to be setters so its easier for faking responses from lower level services?
> Change RestBaseResponse property bag bag to setters from init

- src/RestSharp/Extensions/AsyncHelpers.cs
- src/RestSharp/RestClient.Async.cs
- src/RestSharp/RestClientExtensions.Json.cs
- src/RestSharp/RestClientExtensions.cs
Added back all missing Async API functions (except for json streaming via async not sure how to convert that one).
> Added back all missing Async API functions

- src/RestSharp/RestClient.cs
- src/RestSharp/RestClientOptions.cs
We also need to control the Expect100Continue functionality at the client level. If you need this, doing it at the client level is much better than doing it globally at the ServicePoint level so it does not affect any other requests but those from your client.
Not entirely sure how to best test this
> We also need to control the Expect100Continue functionality at the client level

- src/RestSharp/RestClient.Async.cs
- src/RestSharp/RestClientExtensions.cs
Updates so this works out of the box:
https://github.com/restsharp/RestSharp/issues/1794
> Always stream just the headers for DownloadStreamAsync for best memory utilization

- docs/v107/README.md
Fix a typo in the documentation for v107.
> Fix typo in v107 docs

- .github/workflows/build-dev.yml
- .github/workflows/pull-request.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Set permissions for GitHub actions

- docs/authenticators.md
The token and token type are backwards. When using the current code, it will set the Authorization Header to "[token] Bearer". Switching them around fixes the issue and sets the Authorization Header to "Bearer [token]".
> Fix OAuth2 Example Code

- docs/authenticators.md
Fix parameter order in OAuth2AuthorizationRequestHeaderAuthenticator example in authenticators.md
https://github.com/restsharp/RestSharp/blob/271ddff591c02ebc114ef22239fe139727b3d431/src/RestSharp/Authenticators/OAuth2/OAuth2AuthorizationRequestHeaderAuthenticator.cs#L32-L38
> Fix example in authenticators.md

- docs/usage.md
- src/RestSharp/Extensions/StreamExtensions.cs
- src/RestSharp/Parameters/ObjectParser.cs
- test/RestSharp.Tests/ObjectParserTests.cs
Add a custom attribute to be used with `AddObject` and `GetJsonAsync` to override the property name and format.
Closes #1443 and #1631.
> Added custom props attribute

- src/RestSharp/Request/RequestContent.cs
- test/RestSharp.Tests.Integrated/PostTests.cs
- test/RestSharp.Tests.Integrated/Server/TestServer.cs
Fix for https://github.com/restsharp/RestSharp/issues/1814
> Work around bugs in HttpClient and long form POST data.

- src/RestSharp/Sync/RestClient.Sync.cs
Added `CancellationToken` support into `RestClient.Sync`. It could be helpful for multithreading use case.
> chore: add cancellation support overload

- src/RestSharp/Response/RestResponse.cs
- src/RestSharp/Response/RestResponseBase.cs
- test/RestSharp.Tests.Integrated/StatusCodeTests.cs
- test/RestSharp.Tests.Serializers.Json/NewtonsoftJsonTests.cs
- test/RestSharp.Tests.Serializers.Json/SystemTextJsonTests.cs
* Consider HTTP status code **and** `ResponseStatus` for `IsSuccessful` in `RestResponseBase`
* Added `IsSuccessStatusCode` to `RestResponseBase`
Resolves #1892 
> Fix IsSuccessful in RestResponse (consider ResponseStatus)

- src/RestSharp/Response/RestResponse.cs
This fixes: https://github.com/restsharp/RestSharp/issues/1822
> Do not attempt to read from the stream if we have a ResponseWriter callback

- src/RestSharp/RestClient.cs
> Only add proxy settings to handler if supported

- RestSharp.sln
- src/RestSharp.Serializers.CsvHelper/CsvHelperSerializer.cs
- src/RestSharp.Serializers.CsvHelper/RestClientExtensions.cs
- src/RestSharp.Serializers.CsvHelper/RestSharp.Serializers.CsvHelper.csproj
- test/RestSharp.Tests.Serializers.Csv/CsvHelperTests.cs
- test/RestSharp.Tests.Serializers.Csv/RestSharp.Tests.Serializers.Csv.csproj
- test/RestSharp.Tests.Serializers.Csv/TestObject.cs
I recently started using RestSharp to create a  C# wrapper library for the AlphaVantage financial data REST API. For memory reasons, Alpha Vantage's more data-intensive APIs output only to CSV (not JSON or XML). All its endpoints support CSV responses, so it makes sense to use CSV as the standard data exchange format for the class library I am writing.
As a result, I added CSV serialization support to RestSharp via the robust CsvHelper library. This pull request includes an adapter between RestSharp and CsvHelper that supports both single-line comma-separated records (individual objects) and full CSV tables (collection types inheriting `IEnumerable`). 
So far, I've added tests and tried to mimic the precedents/conventions set by the other serializer projects, but I'm not sure what …
> Add RestSharp.Serializers.CsvHelper

- src/RestSharp/RestSharp.csproj
Fix https://github.com/restsharp/RestSharp/issues/1899
> Set minimum System.Text.Json version to 5.0.1

- docs/usage.md
While following this page and using it a lot while learning APIs, I had an issue where every request I was making to my client, it would reach out to get a new token.  I assume this is not intended, and this was my fix for it.  The local variable 'token' in the GetAuthenticationParameter function doesn't live outside of this and there for the obtained bearer token is never saved to the client object.  I just forced the gettoken function to save to the Token variable that is in AuthenticatorBase.
Please let me know if I am missing something as I would love to learn!  
I do figure that this does not take into account "what if the bearer token expires?"  And to be honest I have no clue how this is handled!  I plan on doing some checks if the request comes back with unauthorized, to get a new …
> Token issues

- src/RestSharp/Authenticators/JwtAuthenticator.cs
- test/RestSharp.Tests/JwtAuthTests.cs
Support constructing JwtAuthenticator with token includes Bearer prefix
This pull request have made to handle scenario of constructing the JwtAuthenticator with token string which includes the Bearer Prefix. For example, Sending http request from one web service to another which use the same jwt secret. In this scenario it is likable to use the Authorization header value from the original request (to the first service). This value includes the Bearer prefix.
Current Behavior: When Passing the value of the existing Authorization attribute to the JwtAuthenticator constructor the result value of the Authorization attribute of the new request will be "Bearer Bearer <TOKEN>"
Expected Behavior: The Authorization header value of the new request will be "Bearer <TOKEN>"
> Support constructing JwtAuthenticator with token includes Bearer prefix

- src/RestSharp/KnownHeaders.cs
- src/RestSharp/Request/RequestHeaders.cs
- src/RestSharp/Request/RestRequest.cs
- src/RestSharp/Request/RestRequestExtensions.cs
- src/RestSharp/Response/RestResponse.cs
- src/RestSharp/RestClient.Async.cs
- src/RestSharp/RestClient.cs
- src/RestSharp/RestClientExtensions.Config.cs
- src/RestSharp/RestClientOptions.cs
- test/RestSharp.Tests.Integrated/RequestTests.cs
- test/RestSharp.Tests.Integrated/Server/TestServer.cs
Implements the following:
- Move handling of Cookies out of HttpClient and into RestSharp, so they will not cross pollinate requests.
- Make the CookieContainer a property on the request, not the client.
- Add tests for cookie handling.
although the breakage is only against stuff that was not released other than in alpha anyway (making Options internal again).
> Move Cookie handling out of HttpClient so we do not cross pollinate requests

- src/RestSharp/RestClient.cs
Add User Agent without validation. It will allow usage of any string as User Agent. Useful for imitating other user agents.
Previous implementation has forbidden multiple characters, which are used in other http clients (not only .net).
#1943 
#1905 
> Add User Agent without validation.

- src/RestSharp/Response/RestResponse.cs
Avoid access to HttpResponseMessage.RequestHeader if the parameter is null.
> fixed access to possible null object RequestMessage

- src/RestSharp/Request/RestRequestExtensions.cs
_Might_ be breaking because we are changing a named argument. Existing call sites that uses [Named argument](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments#named-arguments) might fail to compile.
> cleanup: Fix parameter naming case inconsistency in `RestRequestExtension.cs`

- src/RestSharp/RestClient.Async.cs
Throw exception on using a disposed RestClient instance. We should always throw this one as it is pretty fatal so you would not want this to silently show up in the Exception response value.
If you try to use a disposed instance right now, you get a silent exception buried inside HttpClient. With this change, it will throw immediately and cause the user code to fail as this is a pretty fatal problem.
> Throw exception on disposed RestClient

- src/RestSharp/Parameters/ObjectParser.cs
- src/RestSharp/Request/RestRequestExtensions.cs
- src/RestSharp/RestClientExtensions.Json.cs
Add the `Encode` property to `RequestPropery` attribute, set it to `true` by default.
I would allow disabling the parameter encoding for each of the object properties when using `AddObject` and `GetJsonAsync`.
> Optionally disable encoding for request properties

- src/RestSharp/RestClient.Async.cs
- test/RestSharp.Tests.Integrated/CookieTests.cs
- test/RestSharp.Tests.Integrated/Server/Handlers/CookieHandlers.cs
Related to [issue 1792](https://github.com/restsharp/RestSharp/issues/1792)
When a response contains a Cookie header with an empty domain, the .NET library that parses the cookie throws an exception. This PR ignores cookie parsing exceptions so that the request does not fail due to malformed cookies. Instead, the cookie is ignored and the header is still accessible through the response headers. 
> Bug fix. Response cookie with empty domain fails

- src/RestSharp/Request/RequestContent.cs
- test/RestSharp.Tests.Integrated/HttpHeadersTests.cs
- test/RestSharp.Tests.Integrated/PostTests.cs
- test/RestSharp.Tests.Integrated/RequestHeadTests.cs
- test/RestSharp.Tests.Integrated/Server/Handlers/FormRequest.cs
- test/RestSharp.Tests.Integrated/Server/TestServer.cs
- test/RestSharp.Tests.Serializers.Xml/SampleClasses/twitter.cs
> Added default parameters to the request. They got missing somehow.

- src/RestSharp/Options/RestClientOptions.cs
- src/RestSharp/RestClient.cs
Fixes #1984
- Unsupported options annotated with an attribute
- Only assign options to handler properties if the platform supports them
> Fix unsupported platform issues

- docs/usage.md
- src/RestSharp.Serializers.NewtonsoftJson/JsonNetSerializer.cs
- src/RestSharp/Extensions/StringExtensions.cs
- src/RestSharp/Request/BodyExtensions.cs
- src/RestSharp/Request/RequestContent.cs
- src/RestSharp/Request/RestRequestExtensions.cs
- test/RestSharp.Tests.Integrated/JsonBodyTests.cs
- test/RestSharp.Tests.Integrated/RequestBodyTests.cs
- test/RestSharp.Tests.Integrated/RestSharp.Tests.Integrated.csproj
Proposal to fix #1954.
Add a `AddJsonBody` overload with `string` payload argument with `forceSerialize` argument. If `forceSerialize` is set to true, the string will be serialised. If it's set to `false`, the string will be sent as-is. 
It's not a strictly breaking change, I think it might be released a s a minor version.
> Add `AddJsonBody` overload to serialise top-level string

- src/RestSharp/Extensions/CookieContainerExtensions.cs
- src/RestSharp/Request/RequestHeaders.cs
- src/RestSharp/RestClient.Async.cs
- test/RestSharp.Tests.Integrated/CookieTests.cs
Fixes #2055
* Merge client- and request-level cookies in one header
* Also allows using a manually-set cookie header without overriding it
* Copies response cookies to the client-level container if it is set
* Dispose the response message if not downloading data, it might've been a memory leak. 
> Merge client- and request-level cookies in the header

- src/RestSharp/Request/RequestContent.cs
- src/RestSharp/Request/RestRequest.cs
- src/RestSharp/Request/RestRequestExtensions.cs
- src/RestSharp/RestClient.Async.cs
- test/RestSharp.Tests/RestRequestParametersTests.cs
Support file uploading without multipart/form-data based on #1422
> Support file uploading without multipart/form-data

- src/RestSharp/SimpleClientFactory.cs
Update SimpleClientFactory to use builtin methods to ConcurrentDictionary to avoid adding a key multiple times when run concurrently
- As this resolves a concurrency issue, I find it hard to reliably reproduce in Unit Tests.
> Use builtin methods to ConcurrentDictionary

- benchmarks/RestSharp.Benchmarks/RestSharp.Benchmarks.csproj
- docs/usage.md
- props/Common.props
- src/Directory.Build.props
- src/RestSharp.Serializers.CsvHelper/CsvHelperSerializer.cs
- src/RestSharp.Serializers.CsvHelper/RestSharp.Serializers.CsvHelper.csproj
- src/RestSharp/Parameters/FileParameter.cs
- src/RestSharp/Request/RequestContent.cs
- test/Directory.Build.props
- test/RestSharp.Tests.Integrated/RestSharp.Tests.Integrated.csproj
- test/RestSharp.Tests.Integrated/Server/Handlers/FileHandlers.cs
- test/RestSharp.Tests.Integrated/UploadFileTests.cs
- test/RestSharp.Tests.Serializers.Csv/CsvHelperTests.cs
- test/RestSharp.Tests/RestSharp.Tests.csproj
Use encoded filename for FileNameStar (Fixes #2117)
> Use encoded filename for FileNameStar (#2117)

- docs/usage.md
Remove `Authenticator` from `RestClient` init to `RestClientOptions` in [Usage][2] docs.
Update the [Usage documentation][2] so that it conforms to the [latest RestSharp API][1] regarding where to set the `IAuthenticator? Authenticator`.
New deprecation in [`RestSharp/RestClient.cs`][1]:
```csharp
[Obsolete("Use RestClientOptions.Authenticator instead")]
public IAuthenticator? Authenticator => Options.Authenticator;
```
Deprecation warning `CS0618: 'RestClient.Authenticator' is obsolete: 'Use RestClientOptions.Authenticator instead'` in live:
[1]: https://github.com/restsharp/RestSharp/blob/d0b4b1842859ff3c61c7a6151ba273f3a8577f95/src/RestSharp/RestClient.cs#L52C19-L52C19
[2]: https://restsharp.dev/usage.html#api-client
> Update IAuthenticator? Authenticator in usage.md

- src/RestSharp/Serializers/RestSerializers.cs
1. Choose by request type only when the server didn't provide a content type and it wasn't possible to detect it
2. If the server did provide a content type but we don't have a deserializer for it, try detection as a fallback
If we do have some indication about the content type, either from the response header or from detection, then there's no reason to ignore that information, just because we have no deserializer for it available. If we don't have a matching one for the given situation and parameters, then that's a fact, but it's logically not valid to choose a deserializer by request type.
Now, one might argue that servers are sometimes sending invcorrect headers, which is true of course, but for the case of a possibly (we don't know, we only know that we have no deserializer for it) …
> Adjust serializer selection fallback procedure

- docs/usage.md
- src/RestSharp/RestClient.cs
- test/RestSharp.Tests/RestClientTests.cs
When a UserAgent is set in the RestClientOptions passed to the RestClient constructor, the UserAgent is now set as a HTTP header in the DefaultParameters property rather than modifying the HttpClient instance. This is so that the HttpClient instance can be re-used for APIs etc that require different UserAgent headers.
The ConfigureHttpClient method still sets the max timeout as that's set on the client instance itself, not a HTTP header.
I did not modify the "ExpectContinue" behaviour as it seems to have complex logic around parsing values rather than just directly setting them. If this is something you'd like to be in the DefaultParameters property too I can consider that.
> Set UserAgent as a default header parameter

- src/RestSharp/Authenticators/OAuth/OAuthTools.cs
- test/RestSharp.Tests.Integrated/OAuth1Tests.cs
Fixes OAuth1 signature which is generated wrong when containing special characters
#2126 , #1945 
- [ x] Bugfix (non-breaking change which fixes an issue)
> Fixes OAuth1 signature with special characters (#2126, #1945)

- src/RestSharp/Response/RestResponse.cs
Set Version in `RestResponse<T>`
Fix #2196
> Set Version to generic RestResponse

- src/RestSharp/Options/RestClientOptions.cs
- src/RestSharp/Request/RestRequest.cs
- src/RestSharp/RestClient.Async.cs
- src/RestSharp/RestClient.cs
- test/RestSharp.Tests.Integrated/NonProtocolExceptionHandlingTests.cs
- test/RestSharp.Tests.Integrated/PutTests.cs
- test/RestSharp.Tests.Integrated/RequestTests.cs
1. I think the current approach to use int for timeout is outdated and it generates a lot of errors when you need to remember that these are milliseconds, and you need translate it. Even HttpClient has timeout as TimeSpan.
2. The presence of "MaxTimeout" also confuses many users. If you want to set a custom timeout for the request, you need to remember which timeout is set for the rest client. Often, when you set a custom timeout for request, it's higher timeout than the default. These are requests for downloading and uploading files. It's rare case when the timeout is specially reduced for a particular request.
> Timeout as TimeSpan, Support custom request timeout

- src/RestSharp/Request/RestRequest.cs
- src/RestSharp/RestClient.Async.cs
Makes possible to use a different request version, not just HTTP 1.1. Fixes #2186.
> Add Version to RestRequest

- docs/docs/usage/_category_.json
Fixes the spelling of RestSharp on the intro page at https://restsharp.dev/docs/intro
> Fix spelling in docs sidebar

- gen/SourceGenerator/Extensions.cs
- gen/SourceGenerator/ImmutableGenerator.cs
- gen/SourceGenerator/InheritedCloneGenerator.cs
- gen/SourceGenerator/Properties/launchSettings.json
- gen/SourceGenerator/SourceGenerator.csproj
- src/RestSharp/Extensions/GenerateImmutableAttribute.cs
- src/RestSharp/Extensions/HttpResponseExtensions.cs
- src/RestSharp/Response/RestResponse.cs
- src/RestSharp/Response/RestResponseBase.cs
- src/RestSharp/RestClient.Async.cs
To avoid issues when new properties are added to `RestResponse` but get missed in `FromResponse`, the code generator will take care of generating the function automatically.
> Use code generator for cloning responses

- src/RestSharp/Options/RestClientOptions.cs
- src/RestSharp/RestClient.Extensions.cs
Release [111.0.0](https://github.com/restsharp/RestSharp/releases/tag/111.0.0) broke a few scenarios, with the changes in https://github.com/restsharp/RestSharp/pull/2078 and https://github.com/restsharp/RestSharp/pull/2141.
While both of these changes are valuable, they are breaking changes, and they break code generated by https://github.com/OpenAPITools/openapi-generator.
This PR adds overloads to these methods to re-instate the old behaviour, but flags them as `[Obsolete]`. 
(If projects that consume this library has `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` in the csproj, then this can be overridden via `<<NoWarn>618</NoWarn>`)
> Re-instate old methods, but as obsolete

- Directory.Packages.props
- gen/SourceGenerator/ImmutableGenerator.cs
- src/RestSharp/Authenticators/JwtAuthenticator.cs
- src/RestSharp/Authenticators/OAuth/OAuthWorkflow.cs
- src/RestSharp/Ensure.cs
- src/RestSharp/Options/RestClientOptions.cs
- src/RestSharp/Parameters/DefaultParameters.cs
- src/RestSharp/Parameters/HeaderParameter.cs
- src/RestSharp/Parameters/Parameter.cs
- src/RestSharp/Parameters/ParametersCollection.cs
- src/RestSharp/Parameters/RequestParameters.cs
- src/RestSharp/Parameters/UrlSegmentParameter.cs
- src/RestSharp/Request/HttpRequestMessageExtensions.cs
- src/RestSharp/Request/RequestHeaders.cs
- src/RestSharp/Request/RestRequest.cs
- src/RestSharp/Request/RestRequestExtensions.Headers.cs
- src/RestSharp/Request/UriExtensions.cs
- src/RestSharp/Response/RestResponseBase.cs
- src/RestSharp/RestClient.cs
- test/RestSharp.Tests.Integrated/HttpHeadersTests.cs
- test/RestSharp.Tests.Serializers.Xml/SampleClasses/twitter.cs
- test/RestSharp.Tests/RequestHeaderTests.cs
Ensure that when adding a header parameter with null value, it throws immediately, without waiting for request execution.
Allow multiple header values for one header key, also support properly adding header parameters with multiple values per header.
Fixes #2227
Fixes #2235
> Header value null check

- docs/docs/usage/request.md
- src/RestSharp/Parameters/Parameter.cs
- test/RestSharp.Tests.Integrated/MultipartFormDataTests.cs
POST parameters support content type when being used in multipart forms, but there's no way to set the content type property of the parameter today. This PR fixes it.
> Allow setting parameter content type

- docs/versioned_docs/version-v111/intro.md
> Correct methods name

- docs/versioned_docs/version-v111/usage/example.md
> Correct typo

- src/RestSharp/Response/RestResponseExtensions.cs
I liked the new extensions added in #2221, but immediately wished for the same extensions for the `ContentHeaders` collection. This PR adds `GetContentHeaderValue` and `GetContentHeaderValues` extension methods.
I also removed the `?` after `HeaderParameter.Value` properties in the extensions, as they are no longer needed after #2241.
> Added extensions for getting content header values

- src/RestSharp/Parameters/HeaderParameter.cs
- src/RestSharp/Request/RestRequestExtensions.Headers.cs
- test/RestSharp.Tests/RequestHeaderTests.cs
Fixes potential exposure of applications that use RestSharp and allow users to provide header values to execute a request with CRLF in the header value possibly causing SSRF.
It's breaking change since some users might be required to send invalid header values. Also, the new version is not binary-compatible with the previous version, so the fix will be released as a major version.
> Don't allow CRLF in headers

- .github/workflows/pull-request.yml
- Directory.Packages.props
- benchmarks/RestSharp.Benchmarks/RestSharp.Benchmarks.csproj
- gen/SourceGenerator/Extensions.cs
- gen/SourceGenerator/ImmutableGenerator.cs
- gen/SourceGenerator/InheritedCloneGenerator.cs
- src/Directory.Build.props
- src/RestSharp/Authenticators/OAuth/OAuthTools.cs
- src/RestSharp/Extensions/GenerateImmutableAttribute.cs
- src/RestSharp/Options/RestClientOptions.cs
- src/RestSharp/Response/RestResponse.cs
- src/RestSharp/RestSharp.csproj
- test/Directory.Build.props
- test/RestSharp.InteractiveTests/RestSharp.InteractiveTests.csproj
* Use non-generic attribute for source generation (fixes #2245)
* Add .NET 9.0 target
* Remove .NET 6.0 and 7.0 targets
* Update System.Text.Json dependency to 9.0 (fixes #2268)
> Upgrade to support .NET 9

- src/RestSharp/Parameters/UrlSegmentParameter.cs
- test/RestSharp.Tests/ParametersTests.cs
We need to use path parameters which include the sequence of characters '%2F' or '%2f' in them. The constructor of UrlSegmentParameter replaces these sequences in the value with a '/' character. When using version 110.2.0 of RestSharp we would get around this by setting the Value property with the original string after the creation of the UrlSegmentParameter, but at 112.0.0 this is no longer possible as the Value property is now readonly after creation.
This pull request adds an optional parameter to the UrlSegmentParameter constructor to give control over whether the value is changed to replace '%2F' or not.
(we cannot create a new class with the desired behaviour since the UrlSegmentParameter type is used in this line https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/Request/ …
> Allow leaving encoded slash in UrlSegmentParameter value
