RestSharp.IntegrationTests/Helpers/SimpleServer.cs
I hope this will prevent some of the random failing of unit tests we see on AppVeyor.
Threads can always be tricky but this could be a great first step.
=> SimpleServer Cleanup With Added Try Catches

RestSharp.Tests/JwtAuthTests.cs, RestSharp.Tests/RestSharp.Tests.csproj, RestSharp/Authenticators/JwtAuthenticator.cs, RestSharp/RestSharp.csproj
Added Json Web Token (JWT) Authenticator
https://tools.ietf.org/html/draft-jones-json-web-token
=> Added Json Web Token (JWT) Authenticator

README.markdown
https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestClient.Sync.cs#L34
=> Supports PATCH - update readme

RestSharp.Tests/XmlDeserializerTests.cs, RestSharp/Deserializers/XmlDeserializer.cs
=> Fix XmlDeserializer for case when RootElement depth >1

RestSharp.IntegrationTests/NonProtocolExceptionHandlingTests.cs
but the Web Library grabbed the localised (dutch) text.
=> Fixed a globalisation bug where English text was expected

RestSharp.IntegrationTests/oAuth1Tests.cs, RestSharp/Authenticators/OAuth1Authenticator.cs
Added type specification to parameters added in OAuth1Authenticator if the ParameterHandling is set to UrlOrPostParameters
=> OAuth1Authenticator Parameter Types

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Add issue and pull request templates. Closes #985 
=> Created Issue and PR templates

RestSharp.Tests/UrlBuilderTests.cs, RestSharp/IRestRequest.cs, RestSharp/RestRequest.cs
I had a case where I had to check if some parameters already exist and replace the values, and if they don't, add those value as new. I think It'll be nice if we have this convenience method in the library.
=> AddOrUpdateParameter, convenience method

RestSharp.Tests/JsonTests.cs, RestSharp.Tests/RestSharp.Tests.Signed.csproj, RestSharp.Tests/RestSharp.Tests.csproj, RestSharp.Tests/SampleClasses/BearerToken.cs, RestSharp.Tests/SampleData/bearertoken.txt, RestSharp/Deserializers/JsonDeserializer.cs
=> Added support for '.' in the Name parameter of "DeserializeAs" attribute

RestSharp/RestClient.cs
Add explicit checks for specific characters involved in structured syntax suffix content types before engaging regular expressions, thereby avoiding unnecessary performance degradation for other content types.
(Due to the nature of the change, no further tests are needed - see `StructuredSyntaxSuffixTests.cs`.)
=> Address performance concerns related to handling of structure syntax suffix content types

RestSharp/Http.Sync.cs, RestSharp/Http.cs, RestSharp/IHttp.cs, RestSharp/IRestClient.cs, RestSharp/RestClient.cs
=> Automatic gzip/deflate decompression was made switchable

RestSharp/Http.Async.cs, RestSharp/Http.Sync.cs, RestSharp/Http.cs
1) Improved flexibility without functionality changes
2) TODO resolved: have been merged methods 
RestSharp.Http.ConfigureAsyncWebRequest() and RestSharp.Http.ConfigureWebRequest() 
=> flexibility improved

RestSharp/RestClient.Sync.cs
=> Throw an exception if the download fails

README.md, RestSharp.IntegrationTests/AsyncRequestBodyTests.cs, RestSharp.IntegrationTests/RequestBodyTests.cs, RestSharp/Enum.cs, RestSharp/RestClient.Async.cs, RestSharp/RestClient.Sync.cs
Added new request method called COPY
=> Added new request method: COPY

RestSharp.Tests/HttpBasicAuthenticatorTests.cs, RestSharp.Tests/OAuth1AuthenticatorTests.cs, RestSharp.Tests/RestSharp.Tests.csproj
Added some unit tests for HttpBasicAuthenticator & OAuth1Authenticator as they had a minimal test coverage.
- [x ] I have added tests that prove my fix is effective or that my feature works
=> Authenticator unit tests

RestSharp/RestClient.cs
=> Allowing multiple Default Parameters for same key

RestSharp.Tests/SampleClasses/misc.cs, RestSharp.Tests/SerializerTests.cs, RestSharp.Tests/XmlDeserializerTests.cs, RestSharp/Deserializers/DeserializeAsAttribute.cs, RestSharp/Deserializers/XmlDeserializer.cs, RestSharp/RestRequest.cs, RestSharp/Serializers/SerializeAsAttribute.cs, RestSharp/Serializers/XmlSerializer.cs
=> Xml node with attributes and content at the same time

RestSharp.IntegrationTests/oAuth1Tests.cs, RestSharp/Authenticators/OAuth/OAuthTools.cs
Fixes issue https://github.com/restsharp/RestSharp/issues/1104
=> Fixes #1104

RestSharp/RestSharp.csproj
=> Adding repositoryUrl for Nuget.org

RestSharp/RestClient.Sync.cs, RestSharp/RestClient.cs
On critical error, request is missing in response. This change adds request every time. Based on #1236.
=> Handle request in response every time

RestSharp/RestSharp.csproj
turning on "optimize code" in project settings - otherwise the DLL was showing in debug mode. Not sure why it was turned off? (https://github.com/restsharp/RestSharp/commit/2246eb9acf4573423af7df1a5974a2c62cc01a19#diff-961b195bf1a7fb9868bfa1697c448734)
- I am not sure why it was disabled, but after re-compiling my application still worked. Feel free to reject if there was a specific reason this was turned off.
=> Turning on code optimizations

RestSharp/Parameter.cs
Check if parameter type is a RequestBody, if so then do not require that the name property be filled out.
=> Fix - Issue(s) 1300 and 1351- parameter validation body parameters

RestSharp/IRestClient.cs, RestSharp/Serialization/Xml/DotNetXmlSerializerClientExtensions.cs
- When marking methods obsolete adjust interface accordingly
- Added more overloads to IRestClient interface for testing purposes
=> When marking methods obsolete adjust interface accordingly

RestSharp/Authenticators/JwtAuthenticator.cs
This pull request fixes issue https://github.com/restsharp/RestSharp/issues/1304
- [x ] Bugfix (non-breaking change which fixes an issue)
=> Fixes issue https://github.com/restsharp/RestSharp/issues/1304

RestSharp.Tests/StringExtensionsTests.cs, RestSharp/Extensions/StringExtensions.cs
Fixes the issue described here https://groups.google.com/forum/#!topic/restsharp/6viUqCOrt68
=> Better handling for the case a unicode character gets between chunks

RestSharp.Tests/RestClientTests.cs, RestSharp/RestClientExtensions.cs
=> Ability to add multiple default headers by passing in a dict

docs/.vuepress/config.js
In vuepress config, the docBranch property is set to master.
I changed it to use the current default branch (i.e: dev).
Fixes: #1527 
=> Fix broken link

src/RestSharp/Parameter.cs
=> Made the Parameter class no obsolete

src/RestSharp/RequestBody.cs, test/Directory.Build.props
=> Remove obsolete attribute from RequestBody constructor

src/RestSharp/Response/RestResponse.cs, test/RestSharp.IntegrationTests/StatusCodeTests.cs
Closes #1675
This PR fixes the issue outlined in #1675. 
- [-] I have added necessary documentation (if appropriate)
=> Fix IsSuccessful on RestResponse<T>

src/RestSharp/RestClient.Serialization.cs
DetectContentType now supports JSON arrays
=> Support json with arrays on DetectContentType.

docs/intro.md
Unnecessary semicolon removed from documentation.
=> Unnecessary semicolon removed in v107 documentation

src/RestSharp/Response/ResponseHandling.cs
=> Fixing incorrect BOM handling in the response 

README.md
Update the status badge in README to link to the Nuget Package page. 
There is no other place in the repository which links to NuGet.
=> Readme links to Nuget page from the badge

docs/v107/README.md
=> fixed a typo

CONTRIBUTING.md
=> Update getting help link location.

src/RestSharp.Serializers.CsvHelper/CsvHelperSerializer.cs
=> Use supplied CsvConfiguration when reading

docs/usage.md
Minor documentation fix (edit spelling error)
=> [Docs] Fix minor typo in usage.md

src/RestSharp/Request/RequestContent.cs, src/RestSharp/Request/RestRequest.cs, test/RestSharp.Tests.Integrated/MultipartFormDataTests.cs
=> Consider the boundary quotes request option value

docs/intro.md
=> fix typo *about* to *above*

src/RestSharp/KnownHeaders.cs
=> Use case insensitive comparer

docs/versioned_docs/version-v111/usage/example.md
=> Correct typo

docs/versioned_docs/version-v111/intro.md
Fixed a sentence that accidentally used the word "only" twice.
=> Fixed sentence to be easier to read

docs/docs/usage/client.md
=> Fixed the Simple Factory example. Fixes #2255
